xcb: mark parameters as unused with QT_NO_CLIPBOARD in QXcbDrag::setActionList
The build was failing with this error:

[...]/qxcbdrag.cpp: In member function ‘void QXcbDrag::setActionList(Qt::DropAction, Qt::DropActions)’:
[...]/qxcbdrag.cpp:575:45: error: unused parameter ‘requestedAction’ [-Werror=unused-parameter]
  575 | void QXcbDrag::setActionList(Qt::DropAction requestedAction, Qt::DropActions supportedActions)
      |                              ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
[...]/qxcbdrag.cpp:575:78: error: unused parameter ‘supportedActions’ [-Werror=unused-parameter]
  575 | void QXcbDrag::setActionList(Qt::DropAction requestedAction, Qt::DropActions supportedActions)
      |                                                              ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors

Amends cc1d891b8ed1c4f23183e4b06f46e5840a993e35.

Change-Id: Ie4c8b425a1f07d062db242f962be3055a0e9db61
Reviewed-by: Liang Qi <liang.qi@qt.io>
(cherry picked from commit 4802ee3c6cd167473acf22eee7b5ee3c94a4a7d5)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>
(cherry picked from commit 64176f7d81a4d0b51d705a8129225402d061a0f9)
(cherry picked from commit 6705b9e2aa6ccc176cf8815709c7c2a3d5854525)
(cherry picked from commit 001cd58a5880bdf8e592215213fce71f8cd8b51b)