util/{unicode,xkbdatagen}: fix build with `REUSE-IgnoreStart`
Building util/unicode I get:
main.cpp:3368:7: error: invalid preprocessing directive #REUSE
 3368 |     # REUSE-IgnoreStart
      |       ^~~~~
main.cpp:3374:7: error: invalid preprocessing directive #REUSE
 3374 |     # REUSE-IgnoreEnd
      |       ^~~~~

Amends a53be8b935964836b643f1b40d56fe16a35cf9c4.

Change-Id: I21c5c6ecc0a8095d74c3721acf77274a1cc78d60
Reviewed-by: Alexandru Croitor <alexandru.croitor@qt.io>
Reviewed-by: Marc Mutz <marc.mutz@qt.io>
(cherry picked from commit 14f0f48487e5a8797ef412887ffa357d6c48aaae)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>
(cherry picked from commit d5d7ecf0fd27e95dc3dd0ae5c1670e4da2249f50)