Fix build with disable-deprecated 6.6: QList is forward-defined
qtbase\src\corelib\compat\removed_api.cpp(763): error C2027: use of undefined type 'QList<QString>'
qtbase/src/corelib/tools/qcontainerfwd.h(40): note: see declaration of 'QList<QString>'
qtbase\src\corelib\compat\removed_api.cpp(1307): error C2027: use of undefined type 'QDynamicMetaObjectData'
qtbase/src/corelib/kernel/qobject.h(43): note: see declaration of 'QDynamicMetaObjectData'

Manual conflict resolution for 6.8:
- dropped the changes to the 6.9 section, absent in this branch,
  naturally.

Fixes: QTBUG-141994
Change-Id: I63324a2cc3b89c62d9ecfffd07b7b82e4ea72641
Reviewed-by: Marc Mutz <marc.mutz@qt.io>
(cherry picked from commit 5dbb3b358950726447765e4fea7feb040a303860)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>
(cherry picked from commit c76f026c0acbd58a61404479b5120bd61dc702ef)
Reviewed-by: Volker Hilsheimer <volker.hilsheimer@qt.io>